# configuration.yaml
# Core configuration for HomeAssistant

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret location_ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Control for web interface
http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret web_interface_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Logging
logger:
  default: warn
  logs:
    #homeassistant.components.wemo: debug
    homeassistant.components.device_tracker.mqtt: debug

# Notifications
notify:
  platform: slack
  api_key: !secret slack_api_key
  default_channel: '#general'

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Discover some devices automatically
# Disabled to stop unwanted devices appearing
#discovery:

######## INCLUDES ########
automation: !include automation.yaml
group: !include groups.yaml
script: !include scripts.yaml


######## ADDITIONAL COMPONENTS ########
# Text to speech
tts:
  platform: google

# MQTT
mqtt:

######## DEVICES ########
# Sonos
media_player:
  - platform: sonos
    hosts:
      - 192.168.1.135
      - 192.168.1.136

# Hive
hive:
  username: !secret hive_username
  password: !secret hive_password
  minutes_between_updates: 5
  devices:
    - hive_heating
    - hive_thermostat_batterylevel
    - hive_heating_state

# Ring Doorbell
ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

# Lights
light:
  - platform: mqtt
    name: "Lounge Table Lamp"
    command_topic: "cmnd/sonoff-lounge-table-lamp/POWER"
    state_topic: "stat/sonoff-lounge-table-lamp/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 1
    retain: true

  - platform: mqtt
    name: "Lounge Floor Lamp"
    command_topic: "cmnd/sonoff-lounge-floor-lamp/POWER"
    state_topic: "stat/sonoff-lounge-floor-lamp/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 1
    retain: true
